### ISSUE TITLE
tp11 ej_14

### ISSUE THREAD

**Issue by svillanueva22** [PI-ITBA/2024_02#155]
Buenas noches! El ejercicio pide crear un TAD para listas de elementos no repetidos que la permita recorrer en forma ascendente o según orden de inserción. Mi duda está en la implementación de la función add, donde utilice dos funciones recursivas distintas, una para agregar en orden ascendente y otra según orden de inserción. El tema es que así me quedan dos listas distintas dentro del CDT, algo así:

**Comment by ImNotGone** [comment]
No se pego el codigo. De todas formas no es necesario una funcion recursiva para insertar en orden de llegada.

**Comment by svillanueva22** [comment]
Es verdad. Igual sigo teniendo la duda de si sería ineficiente tener dos listas distintas en el CDT o si me deberia alcanzar con tener un solo nodo por elemento agregado con dos tails, uno para el orden de inserción y otro para el orden ascendente.

**Comment by svillanueva22** [comment]
Y si la función de orden de llegada no es recursiva, ¿cómo verificaría que el elemento que se quiere agregar no está repetido?

**Comment by ImNotGone** [comment]
podes tener los nodo duplicados y 2 listas o como bien decis, tener un unico nodo con 2 colas, una para asc y una para orden de llegada.

Si tenes los nodos duplicados, para saber si insertas o no podes primero hacer un llamado a la recursiva (orden asc) y si esa inserto, insertar tambien en la de orden de llegada.

Si tenes 2 colas por cada nodo es bastante similar. Tendrias que fijarte si deberias insertar, recorriendo quizas la asc y teniendo la direccion del nodo nuevo, actualizas la cola del ultimo insertado anterior y asignas el nuevo nodo como el ultimo insertado.

**Comment by svillanueva22** [comment]
Impecable, muchas gracias!!!!!
