### ISSUE TITLE
Ej Parcial 1C 2018

### ISSUE THREAD

**Issue by mipipet** [PI-ITBA/2024_02#18]
Hola! Hice el ejercicio del cuadrado mágico de un recuperatorio viejo y quería consultar si sería eficiente mi programa. Le arme un programa de testeo y corría bien. Desde ya muchas gracias!
![Screenshot 2024-09-04 122918](https://github.com/user-attachments/assets/058eefe0-45ab-4edc-b656-eab83eb7a26d)
```c
#include <stdio.h>
#include <assert.h>
#define dim 4
#define n 16

int cuadradoMagico(int m[][dim]); 
int todosElems(int m[][dim]);
int mismaSum(int m[][dim]); 
int sumElems(int * v); 


int main(){
    int m1[][dim]={{16,3,2,13},{5,10,11,8},{9,6,7,12},{4,15,14,1}} ; 
    assert(cuadradoMagico(m1)==1); 
    int m2[][dim]={{16,4,5,10},{11,2,3,6},{12,9,13,15},{7,8,1,14}} ; 
    assert(cuadradoMagico(m2)==0); 
    printf("OK!\n"); 
    return 0; 
}

int cuadradoMagico(int m[][dim]){
    return todosElems(m) && mismaSum(m);
}

int todosElems(int m[][dim]){ 
    int ocupado[n]={0}; // vector de flags 0 --> no está
    for(int i=0; i<dim; i++){
        for(int j=0; j<dim; j++){
            if(m[i][j]<=n && m[i][j]>0){
                if(!ocupado[m[i][j]-1]){
                    ocupado[m[i][j]-1]=1; 
                }else{ //esta repetido
                    return 0; 
                }
            }else{ //no esta en el rango
                return 0; 
            }
        }
    }
    return 1; 
}

int mismaSum(int m[][dim]){
    int i=0, aux=0;
    int sum=sumElems(m[i]); 
    for(int i=0; i<dim; i++){
        aux=0; 
        for(int j=0; j<dim; j++){
            aux+=m[j][i]; //sumo la columna
        }
        if(aux!=sum || sumElems(m[i])!=sum){
            return 0; 
        }
    }
    return 1; 
}

int sumElems(int * v){
    int sum=0; 
    for(int i=0; i<dim; i++){
        sum+=v[i];
    }
    return sum; 
}
```

**Comment by ImNotGone** [comment]
Esto lo podes reescribir, para que te quede menos indentado.
```c
if(m[i][j]<=n && m[i][j]>0){
                if(!ocupado[m[i][j]-1]){
                    ocupado[m[i][j]-1]=1; 
                }else{ //esta repetido
                    return 0; 
                }
            }else{ //no esta en el rango
                return 0; 
            }
```
Asi:
```c
if(!(m[i][j]<=n && m[i][j]>0) || ocupado[m[i][j]-1]){
     return 0;
}
ocupado[m[i][j]-1]=1; 
```

**Comment by ImNotGone** [comment]
La primer fila la sumas 2 veces, quizas si adaptas el codigo podes saltearte eso, pero justo en este caso es un for con 4 iteraciones quizas no es tan critico. Nose si vale la pena, @marcelogarberoglio ¿opiniones?

**Comment by marcelogarberoglio** [comment]
Primero opino que se escribe "No se si vale la pena", al menos en mi época era así
Hacer la suma afuera no estaría mal, la alternativa es chequear todo el tiempo si es la primera fila o no.
Lo que no me convence son tantos recorridos, primero para verificar si los valores están repetidos y dentro del rango, después para sumar una columna y otro para la fila, cuando al ser cuadrada se podría tener dos aux, en uno sumar [i][j] y en otro [j][i] (sólo válido para matrices cuadradas), e ir verificando si están repetidos a medida que se van sumando. Si bien atenta contra la modularización, estaríamos priorizando la eficiencia

**Comment by mipipet** [comment]
Ahí lo corregí, así sería? 
```c
int cuadradoMagico(int m[][dim]){
    int auxFils=0, auxCols=0, suma=0; 
    for(int i=0; i<dim; i++){
        suma+=m[0][i];  //fijo una suma para comparar siempre con el mismo
    }
    int ocupado[n]={0}; // vector de flags 0 --> no está
    for(int i=0; i<dim; i++){
        auxFils=0; 
        auxCols=0; 
        for(int j=0; j<dim; j++){
           if(!(m[i][j]<=n && m[i][j]>0) || ocupado[m[i][j]-1]){
             return 0;
            }
            ocupado[m[i][j]-1]=1; 
            auxFils+=m[i][j]; 
            auxCols+=m[j][i]; 
        }
        if(auxCols!=suma || auxFils!=suma){
            return 0; 
        }
        
    }
    return 1; 
}
``

**Comment by marcelogarberoglio** [comment]
¿Lo probaste?
Porque esto
 ocupado[m[i][j]-1 
 cuando ocupado[m[i][j] es cero va a dar verdadero, tendría que ser
   if(!(m[i][j]<=n && m[i][j]>0) || ocupado[m[i][j]]){

por otro lado, en ocupado sólo almacenarás unos o ceros, por lo que es un desperdicio que sea un vector de int, podría ser un vector de char
