### ISSUE TITLE
Consulta TPE próximo 

### ISSUE THREAD

**Issue by IgnacioPitaC** [PI-ITBA/2024_02#215]
Buenas noches Marcelo, me disculpo por adelantado ya que no se si este es el espacio para hacer este tipo de consultas, mi consulta va mas alla de este TP en particular. No puedo anotarme para esta fecha de final porque tengo el examen final de algebra(correlativa) pendiente, y no se si voy a poder rendirlo en diciembre o febrero debido a complicaciones relacionadas. Mi consulta es; en este tipo de casos, si quiero dar el final en una fecha futura, como seria el procedimiento? Ya no tendria el curso para consultar sobre el TP, ni podria confirmar mi presencia en el final.

**Comment by marcelogarberoglio** [comment]
No, no es el ámbito, mandame un mail.
